### PR TITLE
Add 3.0 on other platforms

### PR DESCRIPTION
**Pull request by skupr-anaconda**
`openjdk 11.0.13` requires `zip `on linux platforms

Actions:
1. Bump build number
2. Add license_family
3. Add `patch` to build

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
We probably should add a `dev_url` and `doc_url` to the meta.yaml file

**Review by ScottBailey — CHANGES_REQUESTED** [review]
I suspect the license should be corrected to `BSD-3-Clause`.
`doc_url` and `dev_url` should be added.

**Comment by skupr-anaconda** [comment]
> I suspect the license should be corrected to `BSD-3-Clause`. `doc_url` and `dev_url` should be added.

There is no dev_url :(. The home URL is very old from 2008 year...

And it's not clear what kind of license was used.

**Comment by skupr-anaconda** [comment]
I updated license and added doc_url

**Review by ScottBailey — APPROVED** [review]

**Pull request merged**
